
version: '3.3'

services:
  microservice-demo:
    image: marketplace.gcr.io/google/nginx1
    container_name: microservice-demo
    ports:
      - "8080:80"
    networks:
      - loadgen-network

  loadgen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loadgen
    depends_on:
      - microservice-demo
    networks:
      - loadgen-network
    command: ["-url", "http://microservice-demo", "-c", "10", "-r", "100"]

networks:
  loadgen-network:
    driver: bridge
