on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  push:
    branches:
      - dev

name: eck-lint
jobs:
  operator-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      id: install
    - name: Helm Repo Add
      run: |
        helm repo add elastic https://helm.elastic.co
        helm pull elastic/eck-operator --untar
    - name: Lint Helm Chart
      run: |
        helm lint eck-operator/ -f $GITHUB_WORKSPACE/environments/default/operator.yaml 
  stack-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      id: install
    - name: Helm Repo Add
      run: |
        helm repo add elastic https://helm.elastic.co
        helm pull elastic/eck-stack --untar
    - name: Lint Helm Chart
      run: |
        helm lint eck-stack/ -f $GITHUB_WORKSPACE/environments/default/stack.yaml 