name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get ./cmd/loadgen/
      - name: Test with the Go CLI
        run: go test -v -cover ./...
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.23.x'
        - name: Install dependencies
          run: go get ./cmd/loadgen/
        - name: Build
          run: go build -o loadgen ./cmd/loadgen/main.go

